# Generated by Django 5.1 on 2025-10-08 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canon_order', models.IntegerField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('short_name', models.TextField(blank=True, null=True)),
                ('testament', models.CharField(blank=True, choices=[('OT', 'Old Testament'), ('NT', 'New Testament')], max_length=2, null=True)),
            ],
            options={
                'db_table': 'books',
            },
        ),
        migrations.CreateModel(
            name='TranslationTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True, null=True, unique=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('license', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'translations',
            },
        ),
        migrations.CreateModel(
            name='VerseTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.IntegerField(blank=True, null=True)),
                ('verse_num', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('text_len', models.IntegerField(blank=True, null=True)),
                ('tokens_json', models.JSONField(blank=True, null=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.booktest')),
                ('translation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.translationtest')),
            ],
            options={
                'db_table': 'verses',
            },
        ),
    ]
