# Generated by Django 5.1 on 2025-10-22 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentVerse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.IntegerField(help_text='Denormalized for faster queries')),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(help_text='Denormalized for faster queries', on_delete=django.db.models.deletion.CASCADE, to='api.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_verses', to=settings.AUTH_USER_MODEL)),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_verse_entries', to='api.verse')),
            ],
            options={
                'db_table': 'recent_verses',
                'indexes': [models.Index(fields=['user', 'last_accessed'], name='recent_vers_user_id_26bd94_idx')],
                'unique_together': {('user', 'book', 'chapter')},
            },
        ),
    ]
