# Generated by Django 5.1 on 2025-10-28 17:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_recentverse'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verse_reference', models.CharField(blank=True, help_text="Human-readable reference like 'John 3:16'", max_length=255)),
                ('content', models.TextField(help_text="The user's note content")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(blank=True, help_text='Last time this was synced from client', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_notes', to=settings.AUTH_USER_MODEL)),
                ('verse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_notes', to='api.verse')),
            ],
            options={
                'db_table': 'study_notes',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', '-updated_at'], name='study_notes_user_id_b545a7_idx'), models.Index(fields=['verse'], name='study_notes_verse_i_b1b5dd_idx')],
            },
        ),
    ]
