# Generated by Django 5.1 on 2025-11-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_studynote'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhabit',
            name='location',
            field=models.CharField(default='home', max_length=255),
        ),
        migrations.AddField(
            model_name='userhabit',
            name='skipped',
            field=models.BooleanField(default=False),
        ),
    ]
