# Generated by Django 5.1 on 2025-11-02 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_studynote'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhabit',
            name='location',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='userhabit',
            name='skipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userhabit',
            name='time',
            field=models.TimeField(verbose_name='Reminder Time'),
        ),
    ]
