# Generated by Django 5.1 on 2025-11-03 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userhabit_location_userhabit_skipped_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhabit',
            name='day',
        ),
        migrations.RemoveField(
            model_name='userhabit',
            name='reminder',
        ),
    ]
