# Generated by Django 5.1 on 2025-11-18 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customuser_avatar'),
        ('api', '0005_remove_userhabit_day_remove_userhabit_reminder'),
    ]

    operations = [
    ]
