# Generated by Django 5.1 on 2025-11-24 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_merge_20251118_2233'),
        ('api', '0007_remove_email_verified_fields'),
    ]

    operations = [
    ]
