# Generated by Django 5.1 on 2025-11-24 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customuser_email_verified_and_more'),
        ('api', '0007_remove_email_verified_fields'),
    ]

    operations = [
    ]
