# Generated by Django 5.1 on 2025-11-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_20251124_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Email verification status'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_verification_email_sent',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last verification email sent', null=True),
        ),
    ]
