# Generated by Django 5.1 on 2025-12-20 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='chapter_count',
            field=models.IntegerField(default=0, help_text='Total number of chapters in this book'),
        ),
    ]
