# Generated by Django 5.1 on 2025-12-20 23:16

from django.db import migrations
from django.db.models import Max


def populate_chapter_counts(apps, schema_editor):
    """Calculate and populate chapter_count for each book based on existing verses."""
    Book = apps.get_model('api', 'Book')
    Verse = apps.get_model('api', 'Verse')

    for book in Book.objects.all():
        # Get the maximum chapter number for this book across all translations
        max_chapter = Verse.objects.filter(book=book).aggregate(
            max_chapter=Max('chapter')
        )['max_chapter']

        if max_chapter is not None:
            book.chapter_count = max_chapter
            book.save()


def reverse_populate_chapter_counts(apps, schema_editor):
    """Reset chapter_count to 0 when reversing migration."""
    Book = apps.get_model('api', 'Book')
    Book.objects.all().update(chapter_count=0)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_book_chapter_count'),
    ]

    operations = [
        migrations.RunPython(populate_chapter_counts, reverse_populate_chapter_counts),
    ]
