# Generated by Django 5.1 on 2026-01-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_populate_chapter_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, help_text='When user requested account deletion', null=True),
        ),
    ]
